Proj 5 deactivate delete playlist
KBSC2/Soundify pull request #19
Opened 2020-11-17 11:13 UTC by sanderpol

This pull request applies to the following story: <https://app.asana.com/0/>

## Description
Deactivation&Deletion added for playlist
**Changes proposed in this pull request (technical):**
* Added Functions into controller
* Added two tests 
* Added two columns to Playlist model

## Checklist:
- [ ] :clipboard: All tests are correct / working

2020-11-17 11:17 UTC, PaulRill00 requested changes

2020-11-17 11:17 UTC, PaulRill00 commented on Controller/DbControllers/PlaylistController.cs
> +        public void deactivatePlaylist(int playlistID)
Functies moeten met een hoofdletter

2020-11-17 11:17 UTC, PaulRill00 commented on Controller/DbControllers/PlaylistController.cs
> +        public void deletePlaylistOnDateStamp()
idem dito

2020-11-17 11:17 UTC, PaulRill00 commented on Tests/ControllorDeactivate-DeletePlaylist.cs
> +        public void SetUp()
Heb je de database niet nodig?

SShClient

2020-11-18 08:55 UTC, PaulRill00 approved these changes

2020-11-18 08:55 UTC, SietseBijlsma approved these changes

2020-11-18 09:06 UTC, merged