Play song, info and slide bar
KBSC2/Soundify pull request #3
Opened 2020-11-11 15:01 UTC by SietseBijlsma

This pull request applies to the following story: <https://app.asana.com/0/>

## Description

you can play a song now.
added play and pause button
added slide bar

**Changes proposed in this pull request (technical):**
*
class Song
class DataContext
class Data
*

## Checklist:
- [ ] :nerd_face: Documentation for this PR is covered.
- [ ] :clipboard: All tests are correct / working

2020-11-11 15:05 UTC, PaulRill00 requested changes

2020-11-11 15:05 UTC, PaulRill00 commented on Model/Song.cs
> +        public double TotalTimeSong {
Can be converted to lambda

2020-11-11 15:08 UTC, sanderpol commented on Model/Song.cs
> +        }
Should be formatted to the correct timestamp --:--

2020-11-12 13:38 UTC, PaulRill00 approved these changes

2020-11-12 13:38 UTC, VincentVinTin approved these changes

2020-11-12 13:39 UTC, merged