Test mainwindow
KBSC2/Soundify pull request #97
Opened 2020-12-15 09:52 UTC by VincentVinTin

This pull request applies to the following story: https://app.asana.com/0/1199140982001301/1199140982001381

## Description
Test maked for buttons from the audioplayer. Also maked a shuffle function and rewritten the fill queue. Many bugs solved.

**Changes proposed in this pull request (technical):**
* Fill queue function maked 
* Shuffle function maked
* Test maked

## Checklist:
- [ ] :nerd_face: Documentation for this PR is covered.
- [ ] :clipboard: All tests are correct / working

2020-12-15 15:11 UTC, PaulRill00 approved these changes

2020-12-15 15:12 UTC, SietseBijlsma approved these changes

2020-12-15 15:14 UTC, SietseBijlsma submitted a review, later dismissed

2020-12-15 15:47 UTC, PaulRill00 requested changes

2020-12-15 15:47 UTC, PaulRill00 commented on View/DataContexts/DataContext.cs
>          public User CurrentUser => UserController.CurrentUser == null ? null : UserController.Create(new DatabaseContext())
`DatabaseContext.Instance`

2020-12-15 15:47 UTC, PaulRill00 commented on View/DataContexts/DataContext.cs
>          public Role CurrentUserRole => UserController.CurrentUser == null ? null : RoleController.Create(new DatabaseContext()).GetItem(UserController.CurrentUser.RoleID);
`DatabaseContext.Instance`

2020-12-15 15:47 UTC, PaulRill00 commented on View/DataContexts/DataContext.cs
> +        public string DisplayName => IsArtist ? ArtistController.Create(new DatabaseContext()).GetArtistFromUserId(UserController.CurrentUser?.ID)?.ArtistName
`DatabaseContext.Instance`

2020-12-16 08:40 UTC, SietseBijlsma approved these changes

2020-12-16 08:40 UTC, PaulRill00 approved these changes

2020-12-16 08:41 UTC, merged