Proj   45 albums
KBSC2/Soundify pull request #98
Opened 2020-12-15 14:27 UTC by sanderpol

This pull request applies to the following story: <https://app.asana.com/0/>

## Description

Well albums can be added

**Changes proposed in this pull request (technical):**
* new controller for album and albumartistsong
* new model for album and albumartistsong
* lazy loading proxy added
* migrations for the db

## Checklist:
- [ ] :nerd_face: Documentation for this PR is covered.
- [ ] :clipboard: All tests are correct / working

2020-12-15 15:04 UTC, PaulRill00 requested changes

2020-12-15 15:04 UTC, PaulRill00 commented on Model/Database/Contexts/MockDatabaseContext.cs
> +        public override DbSet<Album> Albums { get; set; }
Van deze en AlbumsArtistSongs moeten nog mock tabbel gemaakt. In de constructor van MockDatabaseContext.

2020-12-15 15:04 UTC, PaulRill00 commented on Model/DbModels/AlbumArtistSong.cs
> +        [ForeignKey("SongId")]
We kunnen foreignkeys toch net zo goed weg laten?
Werkt toch niet.

2020-12-15 15:04 UTC, PaulRill00 commented on Model/DbModels/Artist.cs
> +        public virtual IList<AlbumArtistSong> AlbumArtistSongs { get; set; }
Waarom is dit virtual?

2020-12-15 15:04 UTC, PaulRill00 commented on Model/DbModels/PlaylistSong.cs
> +        public virtual Playlist Playlist { get; set; }
Waarom zijn deze en Song ook virtual?

2020-12-15 15:04 UTC, PaulRill00 commented on Tests/Tests.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="5.0.0" />
Wat doet deze import hier?

2020-12-15 15:08 UTC, SietseBijlsma submitted a review, later dismissed

2020-12-15 15:32 UTC, SietseBijlsma approved these changes

2020-12-15 15:46 UTC, PaulRill00 requested changes

2020-12-15 15:46 UTC, PaulRill00 commented on View/Screens/AlbumUploadScreen.xaml.cs
> +            FileTransfer.Create(new DatabaseContext()).UploadFile(image?.LocalPath, "images/" +
`DatabaseContext.Instance`

2020-12-15 15:46 UTC, PaulRill00 commented on View/Screens/AlbumUploadScreen.xaml.cs
> +            AlbumArtistSongsController.Create(new DatabaseContext()).UploadAlbum(AlbumUploadDataContext.Instance.AlbumSongInfos, image, titleTextBox.Text, description );
`DatabaseContext.Instance`

2020-12-15 15:46 UTC, PaulRill00 commented on View/DataContexts/AlbumUploadDataContext.cs
> +        public string ArtistName => ArtistController.Create(new DatabaseContext())
`DatabaseContext.Instance`

2020-12-15 15:46 UTC, PaulRill00 commented on Controller/DbControllers/AlbumArtistSongsController.cs
> +                SongController.Create(new DatabaseContext()).UploadSong(song, albumSongInfo.File.Name);
`DatabaseContext.Instance`

2020-12-16 08:11 UTC, PaulRill00 commented on Model/Model.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="5.0.0" />
Kan deze niet uit dit project?

2020-12-16 08:11 UTC, PaulRill00 commented on Model/Model.csproj
> +    <PackageReference Include="taglib" Version="2.1.0" />
En hebben we deze ook nodig in Models?

2020-12-16 08:31 UTC, RubenHuizenga requested changes
Requests aanmaken en email versturen naar admin voor album approval

2020-12-16 08:51 UTC, RubenHuizenga approved these changes

2020-12-16 08:53 UTC, SietseBijlsma approved these changes

2020-12-16 08:53 UTC, PaulRill00 approved these changes

2020-12-16 08:57 UTC, merged